import { agentV3ZhCN, hanaZhCN, t } from "./../i18n/zh-CN.js";
import type { BootstrapSnapshot } from '@openlab/protocol';
const now = new Date().toISOString();
export const mockSnapshot: BootstrapSnapshot = {
    protocolVersion: 6,
    mode: 'demo',
    project: { id: 'demo-project', name: t("copy241"), rootPath: 'D:\\Research\\TumorMetabolism', openedAt: now },
    primaryAgent: {
        configured: true, name: t("copy232"), avatar: 'sage', role: 'research_partner',
        identity: hanaZhCN.agentProfile.roles.research_partner.identity,
        instructions: hanaZhCN.agentProfile.roles.research_partner.instructions,
        configuredAt: now, updatedAt: now,
    },
    settings: {
        defaultAgentModel: 'deepseek-v4-pro', utilityModel: 'deepseek-v4-flash', maxConcurrentAgentRuns: 3,
        defaultAgentContextBudget: 128000, delegatedAgentContextBudget: 96000,
        developerMode: false,
        securityPolicy: {
            schemaVersion: 1, projectRead: 'allow', workspaceWrite: 'ask', terminalExecution: 'ask', deletion: 'ask',
            networkAccess: 'ask', outsideWorkspace: 'ask', extensionInstall: 'ask', externalTools: 'ask',
        },
    },
    sessions: [
        { id: 'demo-session', projectId: 'demo-project', title: t("copy242"), status: 'idle', updatedAt: now, model: 'openlab-demo' },
        { id: 'older-session', projectId: 'demo-project', title: t("copy243"), status: 'idle', updatedAt: now, model: 'openlab-demo' },
    ],
    activeSessionId: 'demo-session',
    workspace: {
        sessionId: 'demo-session', activeRootId: 'project', note: '', model: 'openlab-demo', conversationFileCount: 0,
        roots: [{ id: 'project', name: t("copy241"), displayPath: 'D:\\Research\\TumorMetabolism', kind: 'project', access: 'ask', status: 'online' }],
    },
    conversationFiles: [],
    turnVariants: [{ turnId: 'demo-turn', activeVariantId: 'demo-variant', locked: false, variants: [{ id: 'demo-variant', turnId: 'demo-turn', assistantNodeIds: ['assistant-demo'], createdAt: now, status: 'completed' }] }],
    workspaceEditPreviews: [],
    workspaceEditGroups: [],
    timeline: [
        { id: 'welcome', kind: 'notice', title: t("copy244"), content: t("copy245"), status: 'completed', timestamp: now, metadata: {} },
        { id: 'user-demo', kind: 'user', content: t("copy246"), timestamp: now, metadata: {} },
        { id: 'reason-demo', kind: 'reasoning', title: t("copy247"), content: t("copy248"), status: 'completed', timestamp: now, agentId: 'supervisor', metadata: {} },
        { id: 'assistant-demo', kind: 'assistant', title: t("copy232"), content: t("copy249"), status: 'completed', timestamp: now, agentId: 'supervisor', metadata: {} },
    ],
    workbench: { tabs: [], maximized: false },
    workbenchContributions: [],
    worktableTemplates: [],
    worktable: { instances: [] },
    workbenchBlueprints: [],
    workbenchInstances: [],
    layoutProposals: [],
    evidenceAnchors: [],
    runRecords: [],
    reviewRequests: [],
    browserProfiles: [],
    browserSessions: [],
    generatedApps: [],
    generatedAppBlueprints: [],
    annotations: [],
    annotationSets: [],
    artifactRevisions: [],
    sourceMaps: [],
    jobs: [],
    toolchains: [],
    toolchainAdapters: [],
    toolRuns: [],
    paperReaders: [],
    agentDefinitions: [{
        id: 'agent-demo', name: t("copy232"), avatar: 'sage', templateId: 'research_lead',
        identity: hanaZhCN.agentProfile.roles.research_partner.identity,
        instructions: hanaZhCN.agentProfile.roles.research_partner.instructions,
        model: 'openlab-demo', reasoningEffort: 'high', status: 'active', createdAt: now, updatedAt: now,
        toolPolicy: { enabledCapabilityIds: ['workspace.read', 'workspace.write', 'terminal', 'research', 'context', 'collaboration'], disabledToolIds: [], revision: 1 },
        memoryPolicy: { memoryEnabled: false, experienceEnabled: false },
    }],
    agentTemplates: [
        { id: 'research_lead', name: agentV3ZhCN.mock.templates[0][0], summary: agentV3ZhCN.mock.templates[0][1], avatar: 'sage', identity: '# {{agentName}}', instructions: agentV3ZhCN.mock.templates[0][2], source: 'core' },
        { id: 'rigorous_reviewer', name: agentV3ZhCN.mock.templates[1][0], summary: agentV3ZhCN.mock.templates[1][1], avatar: 'ocean', identity: '# {{agentName}}', instructions: agentV3ZhCN.mock.templates[1][2], source: 'core' },
        { id: 'experiment_executor', name: agentV3ZhCN.mock.templates[2][0], summary: agentV3ZhCN.mock.templates[2][1], avatar: 'amber', identity: '# {{agentName}}', instructions: agentV3ZhCN.mock.templates[2][2], source: 'core' },
        { id: 'blank', name: agentV3ZhCN.mock.templates[3][0], summary: agentV3ZhCN.mock.templates[3][1], avatar: 'sage', identity: '# {{agentName}}', instructions: agentV3ZhCN.mock.templates[3][2], source: 'core' },
    ],
    projectAgents: [{ projectId: 'demo-project', agentId: 'agent-demo', enabled: true, externalCapabilityIds: [], updatedAt: now }],
    sessionAgentBinding: { sessionId: 'demo-session', leadAgentId: 'agent-demo', memberAgentIds: [], capabilitySnapshotIds: ['cap-demo'], updatedAt: now },
    capabilitySnapshots: [{ id: 'cap-demo', sessionId: 'demo-session', agentId: 'agent-demo', policyRevision: 1, capabilityIds: ['workspace.read', 'workspace.write', 'terminal', 'research', 'context', 'collaboration'], toolIds: [], createdAt: now }],
    agentRuns: [
        { id: 'run-demo', sessionId: 'demo-session', definitionId: 'agent-demo', name: t("copy232"), role: 'lead', status: 'idle', usage: { promptTokens: 12480, completionTokens: 1620, totalTokens: 14100, cacheHitTokens: 8060, cacheMissTokens: 4420, reasoningTokens: 510 } },
    ],
    toolCapabilities: [
        { id: 'workspace.read', title: agentV3ZhCN.mock.capabilities[0][0], description: agentV3ZhCN.mock.capabilities[0][1], source: 'core', toolIds: ['list_files', 'read_file', 'search_text'], available: true, defaultEnabled: true },
        { id: 'workspace.write', title: agentV3ZhCN.mock.capabilities[1][0], description: agentV3ZhCN.mock.capabilities[1][1], source: 'core', toolIds: ['write_file', 'delete_file', 'undo_change'], available: true, defaultEnabled: true },
        { id: 'collaboration', title: agentV3ZhCN.mock.capabilities[2][0], description: agentV3ZhCN.mock.capabilities[2][1], source: 'core', toolIds: ['delegate_task'], available: true, defaultEnabled: true },
    ],
    memorySummaries: [{ agentId: 'agent-demo', projectId: 'demo-project', pinnedCount: 0, currentCount: 0, experienceCount: 0 }],
    channels: [],
    activeChannelMessages: [],
    tasks: [],
    researchObjects: [
        { id: 'source-1', projectId: 'demo-project', type: 'source', title: t("copy253"), status: 'active', attributes: { version: 2 }, attachments: [], checksum: 'a'.repeat(64), createdBy: { id: 'local-user', kind: 'user' }, createdAt: now, updatedAt: now },
        { id: 'dataset-1', projectId: 'demo-project', type: 'dataset', title: t("copy254"), status: 'active', attributes: { samples: 128 }, attachments: [], checksum: 'b'.repeat(64), createdBy: { id: 'local-user', kind: 'user' }, createdAt: now, updatedAt: now },
        { id: 'evidence-1', projectId: 'demo-project', type: 'evidence', title: t("copy255"), status: 'draft', attributes: { confidence: 'medium' }, attachments: [], checksum: 'c'.repeat(64), createdBy: { id: 'supervisor', kind: 'agent' }, createdAt: now, updatedAt: now },
        { id: 'artifact-1', projectId: 'demo-project', type: 'artifact', title: t("copy256"), status: 'active', attributes: { sha256: '7b6…c12' }, attachments: [], checksum: 'd'.repeat(64), createdBy: { id: 'supervisor', kind: 'agent' }, createdAt: now, updatedAt: now },
    ],
    relations: [
        { id: 'rel-1', projectId: 'demo-project', fromId: 'artifact-1', predicate: 'derivedFrom', toId: 'dataset-1', evidenceIds: [], traceId: 'demo-trace', createdBy: { id: 'supervisor', kind: 'agent' }, createdAt: now },
    ],
    provenance: [
        { artifactId: 'artifact-1', traceId: 'demo-trace', sessionId: 'demo-session', agentId: 'supervisor', model: 'openlab-demo', tool: 'register_artifact', inputObjectIds: ['dataset-1'], inputFileHashes: { 'reports/data-quality.md': '7b6c12' }, createdAt: now },
    ],
    contextPlan: {
        budget: 128000, reservedOutputTokens: 16000, usedTokens: 43280, utilization: 0.386, cacheStableTokens: 21940, compactedRanges: [],
        lastModelRun: { model: 'openlab-demo', usage: { promptTokens: 12480, completionTokens: 1620, totalTokens: 14100, cacheHitTokens: 8060, cacheMissTokens: 4420, reasoningTokens: 510 }, latencyMs: 2180, firstEventLatencyMs: 410, completedAt: now },
        items: [
            { id: 'policy', label: t("copy257"), category: 'policy', priority: 1000, content: t("copy258"), trust: 'trusted', sourceRefs: [], cache: 'stable', estimatedTokens: 6920, included: true },
            { id: 'project', label: t("copy259"), category: 'project', priority: 930, content: t("copy260"), trust: 'trusted', sourceRefs: [], cache: 'stable', estimatedTokens: 5020, included: true },
            { id: 'research', label: t("copy261"), category: 'research', priority: 760, content: t("copy056"), trust: 'untrusted', sourceRefs: ['dataset-1'], cache: 'dynamic', estimatedTokens: 11180, included: true },
            { id: 'conversation', label: t("copy262"), category: 'conversation', priority: 500, content: t("copy263"), trust: 'trusted', sourceRefs: [], cache: 'dynamic', estimatedTokens: 20160, included: true },
        ],
    },
    skills: [],
    mcpServers: [],
    plugins: [],
    pluginCatalog: { status: { source: 'empty', sequence: 0 }, entries: [] },
    pendingApprovals: [],
    providers: [],
    models: [{ id: 'openlab-demo', label: t("copy264"), contextWindow: 128000, supportsThinking: true, supportsTools: true, supportsVision: false }],
};
