const { contextBridge, ipcRenderer, webUtils } = require('electron') as typeof import('electron');

contextBridge.exposeInMainWorld('openlab', {
  getConnection: async () => await ipcRenderer.invoke('runtime:get-connection') as unknown,
  getInterfacePreferences: async () => await ipcRenderer.invoke('interface:get-preferences') as unknown,
  updateInterfacePreferences: async (patch: import('@openlab/protocol').InterfacePreferencesPatch) => await ipcRenderer.invoke('interface:update-preferences', patch) as unknown,
  getWorktableUiState: async (instanceId: string) => await ipcRenderer.invoke('worktable-ui:get', instanceId) as import('@openlab/protocol').WorktableDeviceUiState,
  updateWorktableUiState: async (instanceId: string, patch: Partial<import('@openlab/protocol').WorktableDeviceUiState>) => await ipcRenderer.invoke('worktable-ui:update', instanceId, patch) as import('@openlab/protocol').WorktableDeviceUiState,
  getDeepSeekKeyStatus: async () => await ipcRenderer.invoke('deepseek:key-status') as unknown,
  setDeepSeekKey: async (value: string) => await ipcRenderer.invoke('deepseek:set-key', value) as unknown,
  saveCredential: async (value: string) => await ipcRenderer.invoke('credential:save', value) as unknown,
  chooseProject: async () => await ipcRenderer.invoke('project:choose') as unknown,
  selectProjectFolder: async () => await ipcRenderer.invoke('project:select-folder') as unknown,
  activateProject: async (input: { sourceFolders: string[]; name: string }) => await ipcRenderer.invoke('project:activate', input) as unknown,
  getProjectContext: async () => await ipcRenderer.invoke('project:context') as unknown,
  clearProject: async () => await ipcRenderer.invoke('project:clear') as unknown,
  openProjectFolder: async () => await ipcRenderer.invoke('project:open-folder') as boolean,
  chooseExtension: async (kind: 'skill' | 'plugin') => await ipcRenderer.invoke('extension:choose', kind) as unknown,
  chooseToolchain: async () => await ipcRenderer.invoke('toolchain:choose') as unknown,
  chooseAttachments: async () => await ipcRenderer.invoke('attachment:choose') as unknown,
  importDroppedAttachments: async (files: File[]) => await ipcRenderer.invoke('attachment:import-paths', files.map((file) => webUtils.getPathForFile(file)).filter(Boolean)) as unknown,
  authorizeWorkspaceRoot: async (access: 'read_only' | 'ask' | 'trusted') => await ipcRenderer.invoke('workspace:authorize-root', access) as unknown,
  openWorkspacePath: async (ref: { rootId: string; path: string }) => await ipcRenderer.invoke('workspace:open-path', ref) as boolean,
  importWorkspaceFiles: async (directory: { rootId: string; path: string }) => await ipcRenderer.invoke('workspace:import-files', directory) as unknown,
  pathForDroppedFile: (file: File) => webUtils.getPathForFile(file),
  saveMessagePng: async (dataUrl: string, suggestedName: string) => await ipcRenderer.invoke('message:save-png', dataUrl, suggestedName) as boolean,
  openExternal: async (url: string) => await ipcRenderer.invoke('shell:open-external', url) as boolean,
  exportPlugin: async (id: string, name: string) => await ipcRenderer.invoke('extension:export-plugin', id, name) as boolean,
  exportDiagnostics: async () => await ipcRenderer.invoke('data:export-diagnostics') as boolean,
  backupData: async () => await ipcRenderer.invoke('data:backup') as boolean,
  browser: {
    list: async () => await ipcRenderer.invoke('browser:list') as unknown,
    createProfile: async (input: { name: string; projectId: string }) => await ipcRenderer.invoke('browser:create-profile', input) as unknown,
    authorizeProfile: async (input: { profileId: string; projectId: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:authorize-profile', input) as unknown,
    open: async (input: { profileId: string; projectId: string; instanceId: string; paneId: string; url: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:open', input) as unknown,
    navigate: async (input: { sessionId: string; url: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:navigate', input) as unknown,
    observe: async (sessionId: string) => await ipcRenderer.invoke('browser:observe', sessionId) as unknown,
    act: async (input: { sessionId: string; observationId: string; action: 'click' | 'type' | 'select' | 'press' | 'scroll'; ref?: string; value?: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:act', input) as unknown,
    screenshot: async (input: { sessionId: string; observationId: string }) => await ipcRenderer.invoke('browser:screenshot', input) as unknown,
    readScreenshot: async (resourceId: string) => await ipcRenderer.invoke('browser:read-screenshot', resourceId) as string,
    chooseUpload: async () => await ipcRenderer.invoke('browser:choose-upload') as unknown,
    upload: async (input: { sessionId: string; observationId: string; ref: string; uploadIds: string[]; confirmed: boolean }) => await ipcRenderer.invoke('browser:upload', input) as unknown,
    download: async (input: { sessionId: string; observationId: string; ref: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:download', input) as unknown,
    setBounds: async (input: { sessionId: string; bounds: { x: number; y: number; width: number; height: number }; visible: boolean }) => await ipcRenderer.invoke('browser:set-bounds', input) as boolean,
    hideAll: async () => await ipcRenderer.invoke('browser:hide-all') as boolean,
    close: async (sessionId: string) => await ipcRenderer.invoke('browser:close', sessionId) as unknown,
  },
  window: {
    minimize: () => ipcRenderer.send('window:minimize'),
    maximize: () => ipcRenderer.send('window:maximize'),
    close: () => ipcRenderer.send('window:close'),
  },
});
