const { contextBridge, ipcRenderer, webUtils } = require('electron') as typeof import('electron');

contextBridge.exposeInMainWorld('openlab', {
  getConnection: async () => await ipcRenderer.invoke('runtime:get-connection') as unknown,
  invalidateInactiveRuntimes: async () => await ipcRenderer.invoke('runtime:invalidate-inactive') as boolean,
  getInterfacePreferences: async () => await ipcRenderer.invoke('interface:get-preferences') as unknown,
  updateInterfacePreferences: async (patch: import('@openlab/protocol').InterfacePreferencesPatch) => await ipcRenderer.invoke('interface:update-preferences', patch) as unknown,
  getWorktableUiState: async (instanceId: string) => await ipcRenderer.invoke('worktable-ui:get', instanceId) as import('@openlab/protocol').WorktableDeviceUiState,
  updateWorktableUiState: async (instanceId: string, patch: Partial<import('@openlab/protocol').WorktableDeviceUiState>) => await ipcRenderer.invoke('worktable-ui:update', instanceId, patch) as import('@openlab/protocol').WorktableDeviceUiState,
  getDeepSeekKeyStatus: async () => await ipcRenderer.invoke('deepseek:key-status') as unknown,
  setDeepSeekKey: async (value: string) => await ipcRenderer.invoke('deepseek:set-key', value) as unknown,
  saveCredential: async (value: string) => await ipcRenderer.invoke('credential:save', value) as unknown,
  chooseProject: async () => await ipcRenderer.invoke('project:choose') as unknown,
  selectProjectFolder: async () => await ipcRenderer.invoke('project:select-folder') as unknown,
  activateProject: async (input: { sourceFolders: string[]; name: string }) => await ipcRenderer.invoke('project:activate', input) as unknown,
  stageProject: async (input: { sourceFolders: string[]; name: string }) => await ipcRenderer.invoke('project:create-draft', input) as import('@openlab/protocol').ConversationProjectTarget,
  listProjects: async () => await ipcRenderer.invoke('project:list') as unknown,
  renameProject: async (input: { projectId: string; rootPath: string; name: string }) => await ipcRenderer.invoke('project:rename', input) as import('@openlab/protocol').ConversationSourceDescriptor,
  updateProjectFolders: async (input: { projectId: string; rootPath: string; sourceFolders: string[] }) => await ipcRenderer.invoke('project:update-folders', input) as import('@openlab/protocol').ConversationSourceDescriptor,
  archiveProjectConversations: async (input: { projectId: string; rootPath: string }) => await ipcRenderer.invoke('project:archive-conversations', input) as { archivedSessionIds: string[] },
  removeProject: async (input: { projectId: string; rootPath: string }) => await ipcRenderer.invoke('project:remove', input) as { removed: true; connection?: import('@openlab/protocol').RuntimeConnectionDescriptor },
  listConversationSources: async () => await ipcRenderer.invoke('conversation:sources') as import('@openlab/protocol').ConversationSourceDescriptor[],
  prepareConversationTarget: async (target: import('@openlab/protocol').ConversationProjectTarget) => await ipcRenderer.invoke('conversation:prepare-target', target) as boolean,
  activateExistingProject: async (rootPath: string) => await ipcRenderer.invoke('project:activate-existing', rootPath) as unknown,
  getProjectContext: async () => await ipcRenderer.invoke('project:context') as unknown,
  clearProject: async () => await ipcRenderer.invoke('project:clear') as unknown,
  openProjectFolder: async () => await ipcRenderer.invoke('project:open-folder') as boolean,
  openProjectRoot: async (rootPath: string) => await ipcRenderer.invoke('project:open-root', rootPath) as boolean,
  startConversation: async (input: import('@openlab/protocol').DesktopConversationStartInput) => await ipcRenderer.invoke('conversation:start', input) as import('@openlab/protocol').DesktopConversationStartResult,
  activateConversation: async (input: import('@openlab/protocol').ConversationActivateInput) => await ipcRenderer.invoke('conversation:activate', input) as import('@openlab/protocol').DesktopConversationActivateResult,
  chooseExtension: async (kind: 'skill' | 'plugin') => await ipcRenderer.invoke('extension:choose', kind) as unknown,
  choosePluginCatalogIndex: async () => await ipcRenderer.invoke('plugin-catalog:choose-index') as unknown,
  chooseCuratedPluginPackage: async () => await ipcRenderer.invoke('plugin-catalog:choose-package') as unknown,
  chooseToolchain: async () => await ipcRenderer.invoke('toolchain:choose') as unknown,
  chooseAttachments: async () => await ipcRenderer.invoke('attachment:choose') as unknown,
  importDroppedAttachments: async (files: File[]) => await ipcRenderer.invoke('attachment:import-paths', files.map((file) => webUtils.getPathForFile(file)).filter(Boolean)) as unknown,
  authorizeWorkspaceRoot: async (access: 'read_only' | 'ask' | 'trusted') => await ipcRenderer.invoke('workspace:authorize-root', access) as unknown,
  openWorkspacePath: async (ref: { rootId: string; path: string }) => await ipcRenderer.invoke('workspace:open-path', ref) as boolean,
  importWorkspaceFiles: async (directory: { rootId: string; path: string }) => await ipcRenderer.invoke('workspace:import-files', directory) as unknown,
  pathForDroppedFile: (file: File) => webUtils.getPathForFile(file),
  saveMessagePng: async (dataUrl: string, suggestedName: string) => await ipcRenderer.invoke('message:save-png', dataUrl, suggestedName) as boolean,
  writeClipboardText: async (value: string) => await ipcRenderer.invoke('clipboard:write-text', value) as boolean,
  openExternal: async (url: string) => await ipcRenderer.invoke('shell:open-external', url) as boolean,
  exportPlugin: async (id: string, name: string) => await ipcRenderer.invoke('extension:export-plugin', id, name) as boolean,
  exportDiagnostics: async () => await ipcRenderer.invoke('data:export-diagnostics') as boolean,
  backupData: async () => await ipcRenderer.invoke('data:backup') as boolean,
  browser: {
    list: async () => await ipcRenderer.invoke('browser:list') as unknown,
    createProfile: async (input: { name: string; projectId: string }) => await ipcRenderer.invoke('browser:create-profile', input) as unknown,
    authorizeProfile: async (input: { profileId: string; projectId: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:authorize-profile', input) as unknown,
    open: async (input: { profileId: string; projectId: string; instanceId: string; paneId: string; surface?: 'worktable' | 'workspace_preview'; url: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:open', input) as unknown,
    navigate: async (input: { sessionId: string; url: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:navigate', input) as unknown,
    history: async (input: { sessionId: string; action: 'back' | 'forward' | 'reload' }) => await ipcRenderer.invoke('browser:history', input) as unknown,
    observe: async (sessionId: string) => await ipcRenderer.invoke('browser:observe', sessionId) as unknown,
    act: async (input: { sessionId: string; observationId: string; action: 'click' | 'type' | 'select' | 'press' | 'scroll'; ref?: string; value?: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:act', input) as unknown,
    screenshot: async (input: { sessionId: string; observationId: string }) => await ipcRenderer.invoke('browser:screenshot', input) as unknown,
    readScreenshot: async (resourceId: string) => await ipcRenderer.invoke('browser:read-screenshot', resourceId) as string,
    chooseUpload: async () => await ipcRenderer.invoke('browser:choose-upload') as unknown,
    upload: async (input: { sessionId: string; observationId: string; ref: string; uploadIds: string[]; confirmed: boolean }) => await ipcRenderer.invoke('browser:upload', input) as unknown,
    download: async (input: { sessionId: string; observationId: string; ref: string; confirmed: boolean }) => await ipcRenderer.invoke('browser:download', input) as unknown,
    setBounds: async (input: { sessionId: string; bounds: { x: number; y: number; width: number; height: number }; visible: boolean }) => await ipcRenderer.invoke('browser:set-bounds', input) as boolean,
    hideAll: async () => await ipcRenderer.invoke('browser:hide-all') as boolean,
    close: async (sessionId: string) => await ipcRenderer.invoke('browser:close', sessionId) as unknown,
  },
  window: {
    newWindow: async () => await ipcRenderer.invoke('window:new') as boolean,
    minimize: () => ipcRenderer.send('window:minimize'),
    maximize: () => ipcRenderer.send('window:maximize'),
    close: () => ipcRenderer.send('window:close'),
  },
  edit: {
    command: (command: 'undo' | 'redo' | 'cut' | 'copy' | 'paste' | 'delete' | 'selectAll') => ipcRenderer.send('edit:command', command),
  },
  view: {
    command: (command: 'zoom-in' | 'zoom-out' | 'reset-zoom' | 'toggle-fullscreen' | 'reload') => ipcRenderer.send('view:command', command),
    findInPage: (query: string) => ipcRenderer.send('view:find-in-page', query),
    openTerminal: async () => await ipcRenderer.invoke('view:open-terminal') as boolean,
  },
});
