import { useMemo, useState } from 'react';
import { Archive, Bot, Download, Lock, MessageCircle, Pause, Play, Plus, Square, UsersRound, X } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';
import type { BootstrapSnapshot, CollaborationChannel } from '@openlab/protocol';
import { agentV3ZhCN as copy } from '../i18n/zh-CN.js';
import { formatDateTime } from '../lib/date-time.js';
import { AgentAvatar } from './AgentAvatar.js';
import { SemanticStatus, semanticRoleForStatus } from './SemanticVisual.js';

interface Props {
  snapshot: BootstrapSnapshot;
  timeZone: string;
  onReturnToChat(): void;
  onCreate(input: { name: string; leadAgentId: string; memberAgentIds: string[]; toolAccess?: CollaborationChannel['toolAccess']; minReplies?: number; maxReplies?: number }): Promise<CollaborationChannel | undefined>;
  onActivate(id: string): Promise<void>;
  onUpdate(id: string, patch: Partial<Pick<CollaborationChannel, 'name' | 'toolAccess' | 'minReplies' | 'maxReplies' | 'status'>>): Promise<void>;
  onArchive(id: string): Promise<void>;
  onExport(id: string): Promise<string>;
}

export function ChannelsView({ snapshot, timeZone, onReturnToChat, onCreate, onActivate, onUpdate, onArchive, onExport }: Props) {
  const [creating, setCreating] = useState(false);
  const active = snapshot.channels.find((channel) => channel.id === snapshot.activeChannelId) ?? snapshot.channels[0];
  const definitions = useMemo(() => new Map(snapshot.agentDefinitions.map((agent) => [agent.id, agent])), [snapshot.agentDefinitions]);
  const download = async () => {
    if (!active) return; const markdown = await onExport(active.id); if (!markdown) return;
    const url = URL.createObjectURL(new Blob([markdown], { type: 'text/markdown' })); const link = document.createElement('a'); link.href = url; link.download = `${active.name}.md`; link.click(); URL.revokeObjectURL(url);
  };
  return <main className="channels-view">
    <aside className="channel-list-pane"><header><div><strong>{copy.channels.title}</strong><small>{copy.channels.subtitle}</small></div><button data-testid="create-channel" onClick={() => setCreating(true)}><Plus size={15}/></button></header><nav className="channel-mode-nav"><button data-testid="channels-return-chat" onClick={onReturnToChat}><MessageCircle size={15}/><span>{copy.titlebar.chat}</span></button></nav><div className="channel-list">
      {snapshot.channels.map((channel) => <button key={channel.id} className={channel.id === active?.id ? 'is-active' : ''} onClick={() => void onActivate(channel.id)}><span>{channel.kind === 'private' ? <MessageCircle size={15}/> : <UsersRound size={15}/>}</span><div><strong>{channel.name}</strong><small>{channel.memberAgentIds.map((id) => definitions.get(id)?.name ?? id.slice(0, 6)).join('、')}</small></div><em className={`${channel.status} semantic-${semanticRoleForStatus(channel.status)}`}>{channel.status === 'running' ? copy.channels.running : channel.status === 'paused' ? copy.channels.paused : ''}</em></button>)}
      {!snapshot.channels.length && <div className="channel-list-empty"><UsersRound size={26}/><strong>{copy.channels.emptyTitle}</strong><span>{copy.channels.emptyHint}</span></div>}
    </div></aside>
    <section className="channel-timeline-pane"><header><div><strong>{active?.name ?? copy.channels.defaultTitle}</strong><span><Lock size={12}/>{copy.channels.readonly}</span></div>{active && <button onClick={() => void download()}><Download size={14}/>{copy.channels.exportMarkdown}</button>}</header><div className="channel-readonly-notice"><Lock size={13}/><span>{copy.channels.readonlyHint}</span></div><div className="channel-messages">
      {active && snapshot.activeChannelMessages.map((message) => { const agent = definitions.get(message.fromAgentId); return <article key={message.id}><AgentAvatar avatar={agent?.avatar ?? 'sage'} size="small"/><div><header><strong>{agent?.name ?? message.fromAgentId}</strong><time>{formatDateTime(message.createdAt, timeZone)}</time></header><div className="message-content"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]}>{message.content}</ReactMarkdown></div>{(message.taskId || message.sourceEventIds.length > 0) && <footer>{message.taskId && <span>{copy.channels.task} {message.taskId.slice(0, 8)}</span>}<span>{copy.channels.source} {message.sourceEventIds.length}</span></footer>}</div></article>; })}
      {active && !snapshot.activeChannelMessages.length && <div className="channel-empty"><Bot size={30}/><strong>{copy.channels.waitingTitle}</strong><span>{copy.channels.waitingHint}</span></div>}
      {!active && <div className="channel-empty"><MessageCircle size={30}/><strong>{copy.channels.selectTitle}</strong><span>{copy.channels.selectHint}</span></div>}
    </div></section>
    <aside className="channel-details-pane">{active ? <><header><strong>{copy.channels.settings}</strong><SemanticStatus role={semanticRoleForStatus(active.status)} className={`channel-status ${active.status}`}>{statusLabel(active.status)}</SemanticStatus></header><section><h4>{copy.channels.members}</h4><div className="channel-member-list">{active.memberAgentIds.map((id) => { const agent = definitions.get(id); const run = snapshot.agentRuns.findLast((item) => item.definitionId === id); return <div key={id}><AgentAvatar avatar={agent?.avatar ?? 'sage'} size="small"/><span><strong>{agent?.name ?? id}</strong><small>{id === active.leadAgentId ? copy.channels.channelLead : copy.channels.member} · {run?.status === 'running' ? copy.channels.running : copy.channels.idle}</small></span></div>; })}</div></section><section><h4>{copy.channels.toolCeiling}</h4><select disabled={active.status === 'running'} value={active.toolAccess} onChange={(event) => void onUpdate(active.id, { toolAccess: event.target.value as CollaborationChannel['toolAccess'] })}><option value="read_only">{copy.channels.readOnlyTools}</option><option value="write">{copy.channels.requestWrite}</option></select><p>{copy.channels.capabilityIntersection}</p></section><section><h4>{copy.channels.replyLimits}</h4><div className="channel-reply-limits"><label>{copy.channels.minimum}<input type="number" min={1} max={8} disabled={active.status === 'running'} value={active.minReplies} onChange={(event) => void onUpdate(active.id, { minReplies: Number(event.target.value) })}/></label><label>{copy.channels.maximum}<input type="number" min={1} max={8} disabled={active.status === 'running'} value={active.maxReplies} onChange={(event) => void onUpdate(active.id, { maxReplies: Number(event.target.value) })}/></label></div></section><footer>{active.status === 'running' && <button onClick={() => void onUpdate(active.id, { status: 'paused' })}><Pause size={13}/>{copy.channels.pause}</button>}{active.status === 'paused' && <button onClick={() => void onUpdate(active.id, { status: 'running' })}><Play size={13}/>{copy.channels.resume}</button>}{['running', 'paused'].includes(active.status) && <button onClick={() => void onUpdate(active.id, { status: 'idle' })}><Square size={13}/>{copy.channels.cancel}</button>}<button onClick={() => void onArchive(active.id)}><Archive size={13}/>{copy.channels.archive}</button></footer></> : <div className="channel-details-empty">{copy.channels.selectDetails}</div>}</aside>
    {creating && <CreateChannelModal snapshot={snapshot} onClose={() => setCreating(false)} onCreate={async (input) => { await onCreate(input); setCreating(false); }}/>}
  </main>;
}

function CreateChannelModal({ snapshot, onClose, onCreate }: { snapshot: BootstrapSnapshot; onClose(): void; onCreate(input: { name: string; leadAgentId: string; memberAgentIds: string[]; toolAccess: CollaborationChannel['toolAccess']; minReplies: number; maxReplies: number }): Promise<void> }) {
  const enabled = snapshot.agentDefinitions.filter((agent) => agent.status === 'active' && snapshot.projectAgents.find((binding) => binding.agentId === agent.id)?.enabled);
  const defaultLead = snapshot.sessionAgentBinding.leadAgentId || enabled[0]?.id || '';
  const [name, setName] = useState(''); const [selected, setSelected] = useState<string[]>(defaultLead ? [defaultLead] : []); const [lead, setLead] = useState(defaultLead); const [toolAccess, setToolAccess] = useState<CollaborationChannel['toolAccess']>('read_only'); const [minReplies, setMinReplies] = useState(1); const [maxReplies, setMaxReplies] = useState(3);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 6 ? [...current, id] : current);
  return <div className="agent-create-backdrop" onMouseDown={(event) => event.currentTarget === event.target && onClose()}><div className="channel-create-modal"><header><div><UsersRound size={20}/><span><strong>{copy.channels.createTitle}</strong><small>{copy.channels.createHint}</small></span></div><button onClick={onClose}><X size={17}/></button></header><label>{copy.channels.name}<input autoFocus value={name} placeholder={copy.channels.namePlaceholder} onChange={(event) => setName(event.target.value)}/></label><div className="channel-agent-picker">{enabled.map((agent) => <button key={agent.id} className={selected.includes(agent.id) ? 'is-active' : ''} onClick={() => toggle(agent.id)}><AgentAvatar avatar={agent.avatar} size="small"/><span><strong>{agent.name}</strong><small>{agent.identity.replace(/[#\n]/gu, ' ').slice(0, 48)}</small></span>{selected.includes(agent.id) && <CheckIcon/>}</button>)}</div><div className="channel-create-options"><label>{copy.channels.channelLead}<select value={lead} onChange={(event) => setLead(event.target.value)}>{selected.map((id) => <option key={id} value={id}>{enabled.find((agent) => agent.id === id)?.name ?? id}</option>)}</select></label><label>{copy.channels.toolAccess}<select value={toolAccess} onChange={(event) => setToolAccess(event.target.value as CollaborationChannel['toolAccess'])}><option value="read_only">{copy.channels.readOnly}</option><option value="write">{copy.channels.requestWrite}</option></select></label><label>{copy.channels.minimum}<input type="number" min={1} max={8} value={minReplies} onChange={(event) => setMinReplies(Number(event.target.value))}/></label><label>{copy.channels.maximum}<input type="number" min={1} max={8} value={maxReplies} onChange={(event) => setMaxReplies(Number(event.target.value))}/></label></div><footer><span>{copy.channels.createIdleHint}</span><button className="button secondary" onClick={onClose}>{copy.channels.cancel}</button><button className="button primary" disabled={!name.trim() || selected.length < 2 || !selected.includes(lead)} onClick={() => void onCreate({ name, leadAgentId: lead, memberAgentIds: selected, toolAccess, minReplies, maxReplies })}>{copy.channels.create}</button></footer></div></div>;
}

function CheckIcon() { return <span className="channel-check">✓</span>; }
function statusLabel(status: CollaborationChannel['status']) { return status === 'running' ? copy.channels.running : status === 'paused' ? copy.channels.paused : status === 'archived' ? copy.channels.archived : copy.channels.idle; }
